### ISSUE TITLE
Team Foundation Version Control

### ISSUE THREAD

**Issue by onebeatconsumer** [geeklearningio/gl-vsts-tasks-semver#3]
Forgive me for asking a questions in the issue log. Our goal is to adhere to semantic versioning in our NuGet packages. I am trying to understand:

(1) Whether or not your extension will work with Team Foundation Version Control repository types - we unfortunately do not use Git.

(2) How to tie automated versioning (ex. build numbers) in as variables when packaging.

**Comment by sandorfr** [comment]
First things first, the task in this extension won't help you with the described scenario.

(1) : I don't know of any tool to automatically generate semver numbers from TFSVC. If you really want to pursue with this path I would recommend to consider a migration to git repos. At Geek Learning, we use [GitVersion](https://github.com/GitTools/GitVersion) to achieve such purpose.

(2) : Once you have a computed a semver number you can use our [filepatch extension](https://marketplace.visualstudio.com/items?itemName=geeklearningio.gl-vsts-tasks-file-patch) to modify relevant files prior building and packaging, this is what we do to build our open source nuget package. For instance when it comes to .net core we would use JsonPatch Task to patch ` project.json` files : 
![image](https://cloud.githubusercontent.com/assets/2660262/21741927/22c9f810-d4e4-11e6-98c2-4262f3b236b3.png)

Hope this helps.

**Comment by onebeatconsumer** [comment]
It does. Thank you. We will be using git repos future forward but we have more than 20 applications using tfsvc. Unless you know of a way to migrate existing code to git without losing all the work history, item association, media, etc.

**Comment by sandorfr** [comment]
@onebeatconsumer Microsoft provides a interop and migration tool named [git-tfs](https://github.com/git-tfs/git-tfs) . You have a migration guide in [the documentation](https://github.com/git-tfs/git-tfs/blob/master/doc/usecases/migrate_tfs_to_git.md).

I've never used it so far so I can't give you any feeback in it.

**Comment by onebeatconsumer** [comment]
Sounds promising. I'll have a look. Thanks again, Sandor.
